version: "3.8"

services:
  backend:
    container_name: backend
    image: node:16
    user: node
    volumes:
      - ./backend:/home/node/app
    working_dir: /home/node/app
    tty: true
    networks:
      - network
    ports:
      - 8081:8081
    command: >
      bash -c "npm install && npm run dev"
networks:
  network: